#!/usr/bin/env python3
"""DailyMoney — Business Partnership Agent
Mengelola halaman Kerja Sama / Partnership di website.
Update informasi kontak, media kit, dan testimonial.
Jalan tiap 24 jam via cron.

This agent updates the files generated by generate-site.py,
keeping the site theme but with fresh business content."""
import json, os, subprocess
from datetime import datetime

PROJECT = "/root/workspace/dailymoney-site"
SEND = ["python3", "/root/.hermes/skills/telegram-bridge-send/scripts/send_telegram.py", "--message"]

def send_tg(msg):
    try:
        subprocess.run(SEND + [msg], timeout=15, capture_output=True)
    except:
        pass

def update_kerjasama():
    """Update konten di halaman kerjasama (generated by generate-site.py).
    Kita baca file yang sudah ada, update bagian konten, lalu timpa."""
    paths = [
        ("id", os.path.join(PROJECT, "kerjasama", "index.html")),
        ("en", os.path.join(PROJECT, "en", "kerjasama", "index.html")),
    ]
    updated = 0
    for lang, path in paths:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        
        if lang == "id":
            content = f'''<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Kerja Sama — DailyMoney</title>
<meta name="description" content="Peluang kerja sama, iklan, dan sponsorship dengan DailyMoney — platform edukasi keuangan terpercaya Indonesia.">
<meta property="og:title" content="Kerja Sama — DailyMoney">
<meta property="og:description" content="Iklan, sponsorship, afiliasi, dan partnership dengan DailyMoney.">
<meta property="og:url" content="https://dailymoney.my.id/kerjasama/">
<link rel="canonical" href="https://dailymoney.my.id/kerjasama/">
<link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
<header class="dm-header">
  <a href="/" class="dm-logo"><span class="dm-logo-icon">D</span><span class="dm-logo-text">DailyMoney</span></a>
  <nav class="dm-desktop-nav">
    <a href="/">Beranda</a>
    <a href="/#artikel">Artikel</a>
    <a href="/tentang/">Tentang</a>
    <a href="/kerjasama/" class="active">🤝 Kerja Sama</a>
    <a href="/en/kerjasama/" class="lang-btn">English</a>
  </nav>
</header>

<main>
<section style="padding: 60px 20px; max-width: 1100px; margin: 0 auto;">
  <h1 style="font-size: 2.2em; margin-bottom: 8px;">🤝 Kerja Sama — DailyMoney</h1>
  <p style="color: #64748b; font-size: 1.1em; max-width: 600px;">Platform edukasi keuangan bilingual dengan pertumbuhan organik tinggi. Jadilah bagian dari literasi keuangan Indonesia.</p>

  <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 16px; margin: 32px 0;">
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">10.000+</strong><span style="color: #64748b; font-size: 0.85em;">Pengunjung Bulanan</span></div>
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">100+</strong><span style="color: #64748b; font-size: 0.85em;">Artikel</span></div>
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">2</strong><span style="color: #64748b; font-size: 0.85em;">Bahasa</span></div>
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">10mnt</strong><span style="color: #64748b; font-size: 0.85em;">Update Real-time</span></div>
  </div>

  <h2 style="font-size: 1.4em; margin: 32px 0 16px;">📋 Kategori Kerja Sama</h2>
  <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px;">
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">💰 Iklan & Sponsorship</h3><p style="color: #475569;">Pasang iklan banner, native ads, atau sponsored post. Website finansial dengan traffic organik tinggi dari pencarian Google.</p></div>
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">🤝 Afiliasi & Partnership</h3><p style="color: #475569;">Kerja sama afiliasi produk keuangan — saham, reksadana, emas, crypto, asuransi, fintech. Komisi menarik untuk partner.</p></div>
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">📝 Konten Bersponsor</h3><p style="color: #475569;">Artikel bersponsor dan content collaboration. Tim kami siap membuat konten berkualitas sesuai brand Anda.</p></div>
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">📡 Media & Publikasi</h3><p style="color: #475569;">Press release, liputan media, dan publikasi berita seputar pasar keuangan Indonesia untuk audiens yang tepat.</p></div>
  </div>

  <div style="background: linear-gradient(135deg, #2563eb, #1d4ed8); color: white; border-radius: 12px; padding: 40px; text-align: center; margin: 40px 0;">
    <h2 style="font-size: 1.6em; margin-bottom: 8px;">💬 Tertarik Bekerja Sama?</h2>
    <p style="margin-bottom: 20px; opacity: 0.9;">Hubungi langsung via Telegram untuk diskusi harga dan detail.</p>
    <a href="https://t.me/EsterToobit" style="display: inline-block; background: white; color: #2563eb; padding: 14px 36px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 1.1em;" target="_blank">📱 Hubungi @EsterToobit</a>
    <p style="margin-top: 12px; font-size: 0.85em; opacity: 0.8;">Respon cepat — biasanya dalam 1×24 jam</p>
  </div>

  <div style="background: #eef2ff; border-left: 4px solid #6366f1; border-radius: 8px; padding: 20px; margin: 32px 0;">
    <h3 style="color: #4338ca; margin-bottom: 8px;">📈 Kenapa Iklan di DailyMoney?</h3>
    <p style="color: #475569;">✅ Target audiens tepat: investor, trader, dan masyarakat melek finansial<br>
    ✅ Konten selalu fresh — update harga tiap 10 menit, artikel tiap jam<br>
    ✅ SEO optimasi maksimal — muncul di pencarian Google untuk keyword finansial<br>
    ✅ Bilingual Indonesia & Inggris — jangkauan lebih luas<br>
    ✅ Trafik organik — pengunjung datang karena butuh informasi keuangan</p>
  </div>

  <div style="background: #ecfdf5; border-left: 4px solid #059669; border-radius: 8px; padding: 20px; margin: 32px 0;">
    <h3 style="color: #047857; margin-bottom: 8px;">🏢 Untuk Brand & Perusahaan</h3>
    <p style="color: #475569;">🏦 Bank & fintech — edukasi produk keuangan digital<br>
    📊 Perusahaan sekuritas — perkenalkan platform trading<br>
    💰 Pinjaman online legal — literasi pinjaman bertanggung jawab<br>
    🥇 Emas & logam mulia — edukasi investasi emas<br>
    🏠 Properti — literasi KPR dan investasi properti</p>
  </div>
</section>
</main>

<footer class="dm-footer"><div class="footer-inner"><div class="footer-col"><a href="/" class="logo"><div class="logo-icon">D</div><span>DailyMoney</span></a><p>Platform edukasi keuangan yang membantu Indonesia lebih cerdas secara finansial.</p></div>
<div class="footer-col"><h4>Navigasi</h4><ul><li><a href="/">Beranda</a></li><li><a href="/#artikel">Artikel</a></li><li><a href="/tentang/">Tentang</a></li><li><a href="/kerjasama/">Kerja Sama</a></li><li><a href="/disclosure/">Disclosure</a></li></ul></div>
<div class="footer-col"><h4>Topik</h4><ul><li><a href="/#artikel">Investasi</a></li><li><a href="/#artikel">Saham</a></li><li><a href="/en/">English</a></li></ul></div>
</div><div class="footer-bottom"><p>© 2026 DailyMoney — Platform Edukasi Keuangan Terpercaya</p></div></footer>
</body>
</html>'''
        else:
            content = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Partnership — DailyMoney</title>
<meta name="description" content="Business partnership, advertising, and sponsorship opportunities with DailyMoney — trusted financial education platform in Indonesia.">
<meta property="og:title" content="Partnership — DailyMoney">
<meta property="og:url" content="https://dailymoney.my.id/en/kerjasama/">
<link rel="canonical" href="https://dailymoney.my.id/en/kerjasama/">
<link rel="alternate" hreflang="id" href="https://dailymoney.my.id/kerjasama/">
<link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
<header class="dm-header">
  <a href="/en/" class="dm-logo"><span class="dm-logo-icon">D</span><span class="dm-logo-text">DailyMoney</span></a>
  <nav class="dm-desktop-nav">
    <a href="/en/">Home</a>
    <a href="/en/#artikel">Articles</a>
    <a href="/en/tentang/">About</a>
    <a href="/en/kerjasama/" class="active">🤝 Partnership</a>
    <a href="/kerjasama/" class="lang-btn">Indonesia</a>
  </nav>
</header>

<main>
<section style="padding: 60px 20px; max-width: 1100px; margin: 0 auto;">
  <h1 style="font-size: 2.2em; margin-bottom: 8px;">🤝 Partnership — DailyMoney</h1>
  <p style="color: #64748b; font-size: 1.1em; max-width: 600px;">Bilingual financial education platform with high organic growth. Be part of Indonesia's financial literacy movement.</p>

  <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 16px; margin: 32px 0;">
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">10,000+</strong><span style="color: #64748b; font-size: 0.85em;">Monthly Visitors</span></div>
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">100+</strong><span style="color: #64748b; font-size: 0.85em;">Articles</span></div>
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">2</strong><span style="color: #64748b; font-size: 0.85em;">Languages</span></div>
    <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center;"><strong style="font-size: 1.6em; color: #2563eb; display: block;">10m</strong><span style="color: #64748b; font-size: 0.85em;">Real-time Update</span></div>
  </div>

  <h2 style="font-size: 1.4em; margin: 32px 0 16px;">📋 Partnership Categories</h2>
  <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px;">
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">💰 Advertising & Sponsorship</h3><p style="color: #475569;">Banner ads, native ads, or sponsored posts. High organic traffic from Google financial keyword searches.</p></div>
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">🤝 Affiliate & Partnership</h3><p style="color: #475569;">Affiliate partnership for financial products — stocks, mutual funds, gold, crypto, insurance, fintech.</p></div>
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">📝 Sponsored Content</h3><p style="color: #475569;">Sponsored articles and content collaboration. Our team creates quality content aligned with your brand.</p></div>
    <div style="background: white; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px;"><h3 style="margin-bottom: 8px;">📡 Media & Publication</h3><p style="color: #475569;">Press releases, media coverage, and news publications about Indonesian financial markets.</p></div>
  </div>

  <div style="background: linear-gradient(135deg, #2563eb, #1d4ed8); color: white; border-radius: 12px; padding: 40px; text-align: center; margin: 40px 0;">
    <h2 style="font-size: 1.6em; margin-bottom: 8px;">💬 Interested in Partnership?</h2>
    <p style="margin-bottom: 20px; opacity: 0.9;">Contact via Telegram for pricing and partnership details.</p>
    <a href="https://t.me/EsterToobit" style="display: inline-block; background: white; color: #2563eb; padding: 14px 36px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 1.1em;" target="_blank">📱 Contact @EsterToobit</a>
    <p style="margin-top: 12px; font-size: 0.85em; opacity: 0.8;">Fast response — typically within 24 hours</p>
  </div>
</section>
</main>

<footer class="dm-footer"><div class="footer-inner"><div class="footer-col"><a href="/en/" class="logo"><div class="logo-icon">D</div><span>DailyMoney</span></a><p>Financial education platform helping Indonesians make smarter financial decisions.</p></div>
<div class="footer-col"><h4>Navigation</h4><ul><li><a href="/en/">Home</a></li><li><a href="/en/#artikel">Articles</a></li><li><a href="/en/tentang/">About</a></li><li><a href="/en/kerjasama/">Partnership</a></li><li><a href="/en/disclosure/">Disclosure</a></li></ul></div>
<div class="footer-col"><h4>Topics</h4><ul><li><a href="/en/#artikel">Investment</a></li><li><a href="/en/#artikel">Stocks</a></li><li><a href="/">Indonesia</a></li></ul></div>
</div><div class="footer-bottom"><p>© 2026 DailyMoney — Trusted Financial Education Platform</p></div></footer>
</body>
</html>'''
        
        with open(path, "w") as f:
            f.write(content)
        updated += 1
        print(f"✅ Updated {lang}: {path}")
    
    return updated

def main():
    print(f"{'='*50}")
    print(f"🤝 DailyMoney Business Agent @ {datetime.now().strftime('%d/%m/%Y %H:%M')}")
    print(f"{'='*50}")
    
    n = update_kerjasama()
    msg = f"🤝 *Business Agent*\n✅ Halaman partnership diperbarui ({n} bahasa)\n📅 {datetime.now().strftime('%d %b %H:%M')}"
    print(msg)
    send_tg(msg)

if __name__ == "__main__":
    main()
